credentials:
  usernames:
    diana@diversa.studio:
      email: diana@diversa.studio
      name: Diana
      password: $2b$12$X/Hjv.OXO/MO8Qp5uvn3CuZkF/3gnbs3/Z9Kj2gJcbWJW60/Mdq.C # hashed password

cookie:
  expiry_days: 30
  key: some_random_key
  name: some_random_name

preauthorized:
  emails:
    - diana@diversa.studio
